In [2]:
import numpy as np
from collections import OrderedDict

In [78]:
def sigmoid(X):
  return 1 / ( 1 + np.exp(-X))

In [94]:
class model:
  def network():
    network = OrderedDict()
    network['W1'] = np.random.randn(3,3)
    network['W2'] = np.random.randn(3,3)
    network['W3'] = np.random.randn(3,3)
    network['W4'] = np.random.randn(3,2)
    network['W5'] = np.random.randn(2,2)

    network['B1'] = np.array([1,1,1])
    network['B2'] = np.array([1,1,1])
    network['B3'] = np.array([1,1,1])
    network['B4'] = np.array([1,1])
    network['B5'] = np.array([1,1])
    return network


  def forward(network,X):
    W1,W2,W3,W4,W5 = network['W1'],network['W2'],network['W3'],network['W4'],network['W5']
    B1,B2,B3,B4,B5 = network['B1'],network['B2'],network['B3'],network['B4'],network['B5']

    A1 = np.dot(X,W1) + B1
    print(A1)
    Z1 = sigmoid(A1)
    print(Z1)
    
    A2 = np.dot(Z1,W2) + B2
    print(A2)
    Z2 = sigmoid(A2)
    
    A3 = np.dot(Z2,W3) + B3
    print(A3)
    Z3 = sigmoid(A3)
    
    A4 = np.dot(Z3,W4) + B4
    print(A4)
    Z4 = sigmoid(A4)

    A5 = np.dot(Z4,W5) + B5
    print(A5)
    y = sigmoid(A5)
    return y

  net = network()
  X = np.array([0.3,1.3,-2.2])
  print(X)
  print('------------')
  y = forward(net,X)
  print('---------')
  print(y)

[ 0.3  1.3 -2.2]
------------
[ 3.62533098  0.41136888 -4.3066853 ]
[0.97405101 0.60141607 0.01329891]
[-0.02324939  0.36624546  0.07111518]
[1.5494941  2.30445414 0.95762762]
[-2.7130728   0.51015249]
[1.3658275  1.33979409]
---------
[0.79670519 0.79245608]
